modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "CC0"

[[mods]]
modId = "scriptorresource"
version = "2"
displayName = "Scriptor Debug Mode"
authors = "SSBlur"
description = '''
Enables Debug Mode for Scriptor Magicae.
'''
logoFile = "pack.png"

[[dependencies.scriptorresources]]
modId = "scriptor"
mandatory = true
ordering = "AFTER"
side = "SERVER"
