name: release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Archives
        run: bash ./build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: 
            - scriptor_*.zip
            - scriptor_*.jar
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: 
            - scriptor_*.zip
            - scriptor_*.jar